name: Linting
on: [push, pull_request]
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: errata-ai/vale-action@v1.2.0
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

        # Optional
        config: https://raw.githubusercontent.com/pierrebeitz/vale-test/master/.vale.ini

        # Optional
        files: pages
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

