name: Linting
on: [push, pull_request]
jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: pierrebeitz/vale-action@984edd1b32f97099178101af75a9fcaafd7aa3e2
      with:
        # Optional
        styles: |
          https://github.com/errata-ai/Microsoft/releases/latest/download/Microsoft.zip
          https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip

        # Optional
        config: https://raw.githubusercontent.com/pierrebeitz/vale-test/master/.vale.ini

        # Optional
        files: pages
        onlyAnnotateModifiedLines: 'true'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
