name: Linting

on: [pull_request]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: pierrebeitz/vale-action@41b280003eedd2e9da8633e8b873e4e632077a4f
      with:
        onlyAnnotateModifiedLines: true
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
